<a href="https://colab.research.google.com/github/victorismaelreeves/DataScienceHS/blob/master/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Content

1. <A HREF="https://docs.python.org/3/tutorial/datastructures.html#more-on-lists"> List </A>
2. <A HREF="https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences"> Tuple </A>
3. <A HREF="https://docs.python.org/3/tutorial/datastructures.html#dictionaries"> Dictionary </A>
4. <A HREF="https://docs.python.org/3/tutorial/datastructures.html#sets"> Set </A>
5. <A HREF="https://realpython.com/python-counter/"> Counter </A>




## <font color="green">1. List</font>

### Exercise 1.1

Create `cleared_python_text` by removing all non-letter symbols from the given string `python_text`. Convert to lower case. Create a list of words `python_words`. Print the length of the list.

Hints: str.split, str.replace

In [ ]:
python_text = """
Python is an interpreted high-level general-purpose programming language. Python's design 
philosophy emphasizes code readability with its notable use of significant indentation. Its 
language constructs as well as its object-oriented approach aim to help programmers write clear, 
logical code for small and large-scale projects. Python is dynamically-typed and 
garbage-collected. It supports multiple programming paradigms, including structured (particularly, 
procedural), object-oriented and functional programming. Python is often described as a "batteries 
included" language due to its comprehensive standard library. Guido van Rossum began working on 
Python in the late 1980s, as a successor to the ABC programming language, and first released it in 
1991 as Python 0.9.0. Python 2.0 was released in 2000 and introduced new features, such as list 
comprehensions and a garbage collection system using reference counting. Python 3.0 was released in 
2008 and was a major revision of the language that is not completely backward-compatible and much 
Python 2 code does not run unmodified on Python 3. Python 2 was discontinued with version 2.7.18 in 
2020. Python consistently ranks as one of the most popular programming 
languages.
"""

In [ ]:
import string

python_text.split()
cleared_python_text = [word.lower().strip(string.punctuation) for word in python_text.split()]
python_words = len(cleared_python_text)

print(cleared_python_text)
print(python_words)



['python', 'is', 'an', 'interpreted', 'high-level', 'general-purpose', 'programming', 'language', "python's", 'design', 'philosophy', 'emphasizes', 'code', 'readability', 'with', 'its', 'notable', 'use', 'of', 'significant', 'indentation', 'its', 'language', 'constructs', 'as', 'well', 'as', 'its', 'object-oriented', 'approach', 'aim', 'to', 'help', 'programmers', 'write', 'clear', 'logical', 'code', 'for', 'small', 'and', 'large-scale', 'projects', 'python', 'is', 'dynamically-typed', 'and', 'garbage-collected', 'it', 'supports', 'multiple', 'programming', 'paradigms', 'including', 'structured', 'particularly', 'procedural', 'object-oriented', 'and', 'functional', 'programming', 'python', 'is', 'often', 'described', 'as', 'a', 'batteries', 'included', 'language', 'due', 'to', 'its', 'comprehensive', 'standard', 'library', 'guido', 'van', 'rossum', 'began', 'working', 'on', 'python', 'in', 'the', 'late', '1980s', 'as', 'a', 'successor', 'to', 'the', 'abc', 'programming', 'language', 'a

### Exercise 1.2

Print all sublists of the list `nucleotides`. Note: [a, c] is a sublist for [a, b, c].

Sample input: `[0, 1]`

Sample output:
*   []
*   [0]
*   [1]
*   [0, 1]


In [ ]:
nucleotides = ['A', 'T', 'G', 'C']

In [ ]:
lists = [[]]

for i in range(len(nucleotides) + 1):
    for j in range(i):
      lists.append(nucleotides[j: i])

print(lists)

[[], ['A'], ['A', 'T'], ['T'], ['A', 'T', 'G'], ['T', 'G'], ['G'], ['A', 'T', 'G', 'C'], ['T', 'G', 'C'], ['G', 'C'], ['C']]


### Exercise 1.3

With list comprehensions create matrix $N \times N$ containing squares of integers starting from $0$. First the first column is filled, then the second, and so on.

In [ ]:
import numpy as np

N = int(input())
matrix = [[j**2 for j in range(N)] for i in range(N)]

print(np.array(matrix))

5
[[ 0  1  4  9 16]
 [ 0  1  4  9 16]
 [ 0  1  4  9 16]
 [ 0  1  4  9 16]
 [ 0  1  4  9 16]]


In [ ]:
# sample output
# [[0, 9, 36]
# [1, 16, 49]
# [4, 25, 64]]

### Exercise 1.4

Create 'decoded' list from 'encoded'

Example: 

```encode_list = [0, [1, 2], 4, [1, 0, 3]]```

```decode_list = [0, 1, 2, 4, 1, 0, 3]```



In [ ]:
encode_list = [0, [1, 2], 4, [1, 0, 3]]
decoded_list = lambda encode_list:[element for item in encode_list for element in decoded_list(item)] if type(encode_list) is list else [encode_list]

print(decoded_list(encode_list))

[0, 1, 2, 4, 1, 0, 3]


## <font color="green">2. Tuple</font>

### Exercise 2.1

Convert string to tuple

In [ ]:
input_str = input('Input string: ')
tuple(input_str)

Input string: hello


('h', 'e', 'l', 'l', 'o')

### Exercise 2.2

Calculate the sum and average for each tuple in the given list. Return a list of `(sum, mean)` tuples

In [ ]:
list_of_tuples = [(1, 2, 6), (2, 3, -6), (3, 4), (2, 2, 2, 2)]
lst1 = []

for i in list_of_tuples:
  x = sum(i)
  y = sum(i) / len(i)
  z=[]
  z.append(x)
  z.append(y)
  lst1.append(tuple(z))

print(lst1)

### Exercise 2.3

Given a list (create one for tests) with strings "name number". Return a tuple of tuples ("name", number) sorted in decreasing order by number. For same numbers sort alphabetically.

In [ ]:
templist = [ (line[1], line) for line in MY_TUPLE ] 
templist.sort()
SORTED_MY_TUPLE = [ line[1] for line in templist ]

### Exercise 2.4

Generate a list with equal length tuples with numbers. Return tuple with element-wise sums.


Sample input: ```[(1, 5), (1, 7), (2, 8)]```

Sample output: ```(4, 20)```

In [6]:
x = [(1, 5), (1, 7), (2, 8)]
a,b,c = x[0], x[1], x[2]
answer= [a[i] + b[i] + c[i] for i in range(len(a))]
print(tuple(answer))


(4, 20)


## <font color="green">3. Dictionary</font>

### Exercise 3.1

Write a program to merge several dictionaries into one. If the keys match, then leave the last encountered element.

In [19]:
dict_1 = {'key1': 10, 'key2': 20}
dict_2 = {'key3': 30, 'key4': 40}
dict_3 = {'key1': 50, 'key5': 60}

dict_1.update(dict_2)
dict_1.update(dict_3)
print(dict_1)

{'key1': 50, 'key2': 20, 'key3': 30, 'key4': 40, 'key5': 60}


### Exercise 3.2

Write a program to merge several dictionaries into one. If the keys match, then leave the first encountered element.

In [23]:
dict_1 = {'key1': 10, 'key2': 20}
dict_2 = {'key3': 30, 'key4': 40}
dict_3 = {'key1': 50, 'key5': 60}

def mergeDict(dict1, dict2):
   dict_3 = {**dict_1, **dict_2}
   for key, value in dict_3.items():
       if key in dict_1 and key in dict_2:
               dict_3[key] = [value , dict1[key]]
   return dict_3
finalDict = mergeDict(dict_3, mergeDict(dict_1, dict_2))
print(finalDict)

{'key1': 10, 'key2': 20, 'key3': 30, 'key4': 40}


### Exercise 3.3

The input is a string `cleared_python_text`. Print the character dictionary of this string. The value is the number of occurrences. Don't use `collections`

In [35]:
# your code here
letter_counts={}
cleared_python_text = input()
for c in cleared_python_text:
  if c not in letter_counts:
    letter_counts[c]=0
  letter_counts[c]=letter_counts[c]+1
print(letter_counts)

hello
{'h': 1, 'e': 1, 'l': 2, 'o': 1}


### Exercise 3.4

Create dictionary `{"word": occurrences}` from `python_words`. Print the most common word and the number of occurrences. Don't use `collections` 

In [36]:
words = input().split()
wordfreq = {}
for i in words:
    if i not in wordfreq:
        wordfreq[i] = 0 
    wordfreq[i] += 1
print(wordfreq )

hello hello
{'hello': 2}


## <font color="green">4. Set</font>

### Exercise 4.1

Input:

a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89];

b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13].

Return set of common elements.

Hint: theme name)


In [61]:
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
x = [element for element in a if element in b]
print(x)

[1, 1, 2, 3, 5, 8, 13]


### Exercise 4.2

Generate random sequence `numbers` with 20 integers >=0 and < 100. Check if numbers are unic.

In [62]:
from random import randint
x = []
for i in range(20):
  n = random.randint(0,100)
  x.append(n)
print(x)

if len(x) > len(set(x)):
  print("true")

[19, 84, 8, 43, 23, 33, 29, 7, 38, 73, 48, 5, 16, 46, 49, 30, 26, 69, 86, 58]


### Exercise 4.3

Generate two lists like in the previous ex. Print all numbers that meet only once.

In [63]:
from random import randint
x = []
y= []
for i in range(20):
  n = random.randint(0,100)
  z = random.randint(0,100)
  x.append(n)
  y.append(z)
print(x, y)

for i in x:
  if i not in y:
    print(i)

[38, 11, 21, 31, 82, 59, 41, 59, 38, 59, 11, 60, 45, 35, 92, 36, 12, 12, 44, 57] [74, 41, 9, 95, 9, 86, 29, 18, 72, 70, 38, 39, 43, 36, 52, 26, 98, 4, 51, 57]
11
21
31
82
59
59
59
11
60
45
35
92
12
12
44


### Exercise 4.4

Print min and max of the given set.

In [64]:
my_set = {i ** 2 // 5 for i in range(100)}
print(max(my_set), min(my_set))

1960 0


## <font color="green">5. Counter</font>

In [68]:
from collections import Counter

### Exercise 5.1

Use Counter to do number 3.3


In [69]:
word = input()
Counter(word)

hello


Counter({'e': 1, 'h': 1, 'l': 2, 'o': 1})

### Exercise 5.2

Use Counter to do number 3.4

In [71]:
words = input()
myDict = Counter(words.split())
print(myDict)

hello hello
Counter({'hello': 2})
